### ISSUE TITLE
Wanting to try out OmniFaces but getting CFE exception

### ISSUE THREAD

**Issue by JayGlass** [omnifaces/showcase#10]
Hi All!  Especially BallusC (I see your answers and help all over StackOverflow!)!

I cloned the GIT repo which included the WAR file from:
https://github.com/omnifaces/omnifaces.git

And I included both heads and 3.x but regardless of if I deploy the war file as is (meaning just using the one that was downloaded during the clone) or deploy it in Eclipse by just right clicking the server->add/remove the project but in both cases I get the following deployment error:

."/showcase-6.3-SNAPSHOT".UndertowDeploymentInfoService: java.lang.ClassNotFoundException: org.primefaces.showcase.filter.CharacterEncodingFilter from [Module "deployment.showcase-6.3-SNAPSHOT.war" from Service Module Loader]

This is on JBoss EAP 7, JDK8 if it matters.

Just wanted to bring it to your attention as you'd think the downloaded WAR would be runnable from the get go!

Thank you!

Jay

PS:  that error occurred when deploying the prebuilt WAR, when I go the add/remove route I get this exception:
java.lang.ClassNotFoundException: org.omnifaces.showcase.exceptionhandlers.EpicFailException

**Comment by BalusC** [comment]
Norepro/old.
