### ISSUE TITLE
Exception on Date functions in OmniFaces showcase site

### ISSUE THREAD

**Issue by zakhdar** [omnifaces/showcase#17]
Dear, 

On the Omnifaces website, on the page "Date (Function)" an exception is raised as soon as the page is loaded (https://showcase.omnifaces.org/functions/Dates)
![Capture d’écran du 2022-10-08 16-14-37](https://user-images.githubusercontent.com/56843747/194717216-9f1307a3-c6f7-41ff-a1fa-c65be842fd19.png)

**Comment by BalusC** [comment]
Ah, it has uncovered a bug in `DateProducer.TemporalDate` behind `#{now}`. Thank you for reporting!
