### ISSUE TITLE
o:socket page says to use o:commandScript that doesn't exist

### ISSUE THREAD

**Issue by dstutz** [omnifaces/showcase#23]
Please update the example on the o:socket page to use h:commandScript.

https://showcase.omnifaces.org/push/socket

```
An alternative is to combine <o:socket> with <o:commandScript>. E.g.

<h:panelGroup id="foo">
    ... (some complex UI here) ...
</h:panelGroup>

<o:socket channel="someChannel" scope="view" onmessage="someCommandScript" />
<h:form>
    <o:commandScript name="someCommandScript" action="#{bean.pushed}" render=":foo" />
</h:form>
```

This component is deprecated since OmniFaces 3.0 because it has been integrated in native JSF since JSF version 2.3 as [<h:commandScript>](https://jakarta.ee/specifications/faces/3.0/vdldoc/html_basic/commandscript) with exactly the same functionality. This component has been removed from OmniFaces since OmniFaces 4.0.

**Comment by BalusC** [comment]
Fixed. Can you report future javadoc issues in https://github.com/omnifaces/omnifaces/issues please?
