### ISSUE TITLE
Showcase down

### ISSUE THREAD

**Issue by allarth** [omnifaces/showcase#4]
http://showcase.omnifaces.org is unavailable again, as is http://snapshot.omnifaces.org

Alessio

**Comment by arjantijms** [comment]
Thanks for the report. As you probably have seen there have been more than a few outages lately. Things started to fail more often right after we upgraded to WildFly.

I've already trimmed the server and tuned the memory settings, but it's still not enough.

Today I put some more advanced monitoring in place for the main showcase, so let's see how that plays out. I'll do the same for the snapshot showcase tomorrow (at the moment it's unfortunately still down).

If this still doesn't work, the next step will be to look at the showcase app itself and see if we can tune anything there, scan for any possible memory leaks, etc. If that *still* doesn't work, we may have to admit that we've outgrown the free OpenShift tier and look for some other options.

**Comment by arjantijms** [comment]
Okay, show case is restarted, but not yet tuned. I've done some experiments today and it seems there are some more options that can be done at the servers, but leaving that for a later date. 

Also still have to profile the showcase app itself to see if we're not accidentally doing something silly ourselves there.

**Comment by srbala** [comment]
Both version of showcase are working, you can close the issue.
